### ISSUE TITLE
Uncaught TypeError when loading EXR files

### ISSUE THREAD

**Issue by mmp** [JimNV/nvis#14]
If I try loading an EXR image, I'm seeing a runtime error (and it's not displaying anything). Here is what the Javascript console says. This is with Chrome v95 on a Mac, FWIW.

And here is a test case (in a ZIP file since github won't let me attach an EXR directly...): [boom.zip](https://github.com/JimNV/nvis/files/7514050/boom.zip)

```
Magic number: 20000630
nvis.js:2600 Version field: {"version":2,"singleTile":false,"longNames":false,"nonImage":false,"multiPart":false}
nvis.js:2610 {"channels":{"name":"channels","type":"chlist","size":55,"values":[{"name":"B","pixelType":1,"pLinear":0,"xSampling":1,"ySampling":1},{"name":"G","pixelType":1,"pLinear":0,"xSampling":1,"ySampling":1},{"name":"R","pixelType":1,"pLinear":0,"xSampling":1,"ySampling":1}]},"chromaticities":{"name":"chromaticities","type":"chromaticities","size":32},"M\u0015<?gÕ>":{"name":"M\u0015<?gÕ>","type":"","size":0},"?\u0017·Ñ8-²½\u001e³¤>_ã¬>compression":{"name":"?\u0017·Ñ8-²½\u001e³¤>_ã¬>compression","type":"compression","size":1,"value":3},"dataWindow":{"name":"dataWindow","type":"box2i","size":16,"values":{"xMin":0,"yMin":0,"xMax":479,"yMax":359}},"displayWindow":{"name":"displayWindow","type":"box2i","size":16,"values":{"xMin":0,"yMin":0,"xMax":479,"yMax":359}},"lineOrder":{"name":"lineOrder","type":"lineOrder","size":1,"value":0},"pixelAspectRatio":{"name":"pixelAspectRatio","type":"float","size":4,"value":1},"renderTimeSeconds":{"name":"renderTimeSeconds","type":"float","size":4,"value":3.247905969619751},"samplesPerPixel":{"name":"samplesPerPixel","type":"int","size":4,"value":16},"screenWindowCenter":{"name":"screenWindowCenter","type":"v2f","size":8,"values":{"x":0,"y":0}},"screenWindowWidth":{"name":"screenWindowWidth","type":"float","size":4,"value":1},"worldToCamera":{"name":"worldToCamera","type":"m44f","size":64}}
nvis.js:2617 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at new NvisEXRFile (nvis.js:2617)
    at FileReader.reader.onload (nvis.js:3913)
NvisEXRFile @ nvis.js:2617
reader.onload @ nvis.js:3913
load (async)
drop @ nvis.js:3910
onFileDrop @ nvis.js:5617
(anonymous) @ nvis.js:5202
```

**Comment by mmp** [comment]
FWIW if I change line 2617 of nvis.js to
```
            let compression = ("compression" in this.attributes) ? this.attributes["compression"].value : EXR_NO_COMPRESSION;
```
then that seems to work around that bug (though I am clueless about Javascript so have no idea if that is right.) However, it then subsequently crashes here:
```
nvis.js:2463 Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at NvisBitBuffer.readUint32 (nvis.js:2463)
    at new NvisEXRFile (nvis.js:2698)
    at FileReader.reader.onload (nvis.js:3913)
readUint32 @ nvis.js:2463
NvisEXRFile @ nvis.js:2698
reader.onload @ nvis.js:3913
load (async)
drop @ nvis.js:3910
onFileDrop @ nvis.js:5617
(anonymous) @ nvis.js:5202
```

**Comment by JimNV** [comment]
Thanks for reporting Matt!

The EXR header should be pretty well-defined, although there are som optional attributes.  However, "compression" is not one of them.

Looking at the EXR header output, there appears to be some garbled attribute inserted before what would be the compression attribute (which is also garbled, but at least ends with "compression".

`"M\u0015<?gÕ�>":{"name":"M\u0015<?gÕ�>","type":"","size":0},"�?\u0017·Ñ8-²�½\u001e³¤>_ã¬>compression":{"name":"�?\u0017·Ñ8-²�½\u001e³¤>_ã¬>compression","type":"compression","size":1,"value":3}`

Apart from the garbled part, this compression attribute should really look like:

`{ "compression": { "name": "compression", "type": "compression", "size": 1, "value": 3 }`

...the value of 3 indicating compression of type ZIP, which _nvis_ should handle.  Is this perhaps an output from PBRT that has gone wrong?  I'm not saying it is for certain, could be something in _nvis_ as well, but I've tested on quite a few EXRs and never seen this behavior before.

**Comment by mmp** [comment]
Hi, Jim! I suspect that this is an issue with nvis's handling of the metadata--e.g. if I run `exrheader` from the OpenEXR distribution, it prints the following. (Running `oiiotool -v --info` also gives reasonable looking output.)

This is indeed pbrt output; pbrt adds a bunch of metadata to images now, but it's all done using regular OpenEXR functions, so I would be surprised if it was garbled.

```
file format version: 2, flags 0x0
channels (type chlist):
    B, 16-bit floating-point, sampling 1 1
    G, 16-bit floating-point, sampling 1 1
    R, 16-bit floating-point, sampling 1 1
chromaticities (type chromaticities):
    red   (0.7347 0.2653)
    green (0 1)
    blue  (0.0001 -0.077)
    white (0.321679 0.337672)
compression (type compression): zip, multi-scanline blocks
dataWindow (type box2i): (0 0) - (479 359)
displayWindow (type box2i): (0 0) - (479 359)
lineOrder (type lineOrder): increasing y
pixelAspectRatio (type float): 1
renderTimeSeconds (type float): 3.24791
samplesPerPixel (type int): 16
screenWindowCenter (type v2f): (0 0)
screenWindowWidth (type float): 1
type (type string): "scanlineimage"
worldToCamera (type m44f):
   (1 0 0 0
    0 0.984808 0.173648 -42.6081
    0 0.173648 -0.984808 195.572
    0 0 0 1)
worldToNDC (type m44f):
   (1.20711 0.0868241 -0.492404 97.7862
    0 1.27559 -0.282792 46.3537
    0 0.173649 -0.984813 195.568
    0 0.173648 -0.984808 195.572)
```

**Comment by JimNV** [comment]
Ah, you're right.  Seems the chromacity attributes weren't read.  And neither the m44f of worldToNDC.

Output above was great help.  Fix to be committed soon.

**Comment by JimNV** [comment]
Have commit a fix to this bug.  Could exist some remaining EXR issues apart from the known ones.  Please report if you find any!

Thanks!
